[build]
  command = "npm run build"
  publish = "static"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["static/telecom-logo.png"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
